/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.JuegoJpaController;
import Entidades.Juego;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario iTC
 */
public class EditarJuego extends javax.swing.JFrame {
    Controlador.JuegoJpaController cjuego= new JuegoJpaController();
     List<Entidades.Juego> listaju = cjuego.findJuegoEntities();
     Entidades.Juego j=new Juego();
     
    /**
     * Creates new form AnadirJuego
     */
    public EditarJuego(int id) {  
        initComponents();
        setResizable(false);
        setLocation(800, 200);
        for (int i = 0; i < listaju.size(); i++) {
            if(id==listaju.get(i).getIdJuego()){
                j=listaju.get(i);
                txtDescripcion.setText(listaju.get(i).getDescripcion());
                txtNombreJuego.setText(listaju.get(i).getNombre());
                txtPrecio.setText(listaju.get(i).getPrecio());
                txtRequisitosMin.setText(listaju.get(i).getRequisitosMIn());
                txtRequisitosrec.setText(listaju.get(i).getRequisitosRec());
                txtRutajuego.setText(listaju.get(i).getDirjuego());
                txtRutaminiatura.setText(listaju.get(i).getDirminiatura());
                txtrutaportada.setText(listaju.get(i).getDirportada());
                if(listaju.get(i).getClasificacion().getTipo().equals("Accion")){
                    btnAccion.doClick();
                }
                 if(listaju.get(i).getClasificacion().getTipo().equals("Terror")){
                    btnTerror.doClick();
                }
                  if(listaju.get(i).getClasificacion().getTipo().equals("Aventura")){
                    btnAventura.doClick();
                }
                 if(listaju.get(i).getClasificacion().getTipo().equals("Multijugador")){
                    btnMultijugador.doClick();
                }
                  if(listaju.get(i).getClasificacion().getTipo().equals("Mundo abierto")){
                    btnMundoAbierto.doClick();
                }
            }
        }
        
    }

    private EditarJuego() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JPeditarJuego = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtNombreJuego = new javax.swing.JTextField();
        SCdes = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtRutajuego = new javax.swing.JTextField();
        SCRR = new javax.swing.JScrollPane();
        txtRequisitosrec = new javax.swing.JTextArea();
        txtRutaminiatura = new javax.swing.JTextField();
        btnAccion = new javax.swing.JRadioButton();
        btnTerror = new javax.swing.JRadioButton();
        btnAventura = new javax.swing.JRadioButton();
        btnMultijugador = new javax.swing.JRadioButton();
        btnMundoAbierto = new javax.swing.JRadioButton();
        GuardarEdicion = new javax.swing.JButton();
        SCRM = new javax.swing.JScrollPane();
        txtRequisitosMin = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtrutaportada = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar Juego");
        setBackground(new java.awt.Color(6, 11, 25));

        JPeditarJuego.setBackground(new java.awt.Color(6, 11, 25));
        JPeditarJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("CLASIFICACION");
        JPeditarJuego.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Candara Light", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("EDITAR JUEGO");
        JPeditarJuego.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("TITULO");
        JPeditarJuego.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("PRECIO$");
        JPeditarJuego.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("DESCRIPCION");
        JPeditarJuego.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("IMAGEN Miniatura");
        JPeditarJuego.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("REQUISITOS MINIMOS");
        JPeditarJuego.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("REQUISITOS RECOMENDADOS");
        JPeditarJuego.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("ARCHIVO DE JUEGO");
        JPeditarJuego.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, -1));

        txtPrecio.setBackground(new java.awt.Color(6, 11, 25));
        txtPrecio.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JPeditarJuego.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 460, -1));

        txtNombreJuego.setEditable(false);
        txtNombreJuego.setBackground(new java.awt.Color(6, 11, 25));
        txtNombreJuego.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        txtNombreJuego.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreJuego.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JPeditarJuego.add(txtNombreJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 460, -1));

        txtDescripcion.setBackground(new java.awt.Color(6, 11, 25));
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setWrapStyleWord(true);
        SCdes.setViewportView(txtDescripcion);

        JPeditarJuego.add(SCdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 460, -1));

        txtRutajuego.setBackground(new java.awt.Color(6, 11, 25));
        txtRutajuego.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        txtRutajuego.setForeground(new java.awt.Color(255, 255, 255));
        txtRutajuego.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRutajuego.setText("rutadescargable");
        txtRutajuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutajuegoActionPerformed(evt);
            }
        });
        JPeditarJuego.add(txtRutajuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 460, -1));

        txtRequisitosrec.setBackground(new java.awt.Color(6, 11, 25));
        txtRequisitosrec.setColumns(20);
        txtRequisitosrec.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        txtRequisitosrec.setForeground(new java.awt.Color(255, 255, 255));
        txtRequisitosrec.setLineWrap(true);
        txtRequisitosrec.setRows(5);
        txtRequisitosrec.setText("Sistema Operativo: Windows 10 64-Bit\nCPU: Intel Core i5-2500K o AMD Ryzen R5 1600X\nRAM: 12 GB de RAM\nHDD (de lanzamiento): 175 GB\nGráficos: NVIDIA GeForce GTX 970 / GTX 1660 Super o Radeon R9 390 / AMD RX 580\nDirectX 12\nConexión a internet");
        txtRequisitosrec.setWrapStyleWord(true);
        SCRR.setViewportView(txtRequisitosrec);

        JPeditarJuego.add(SCRR, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 350, 120));

        txtRutaminiatura.setBackground(new java.awt.Color(6, 11, 25));
        txtRutaminiatura.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        txtRutaminiatura.setForeground(new java.awt.Color(255, 255, 255));
        txtRutaminiatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRutaminiatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaminiaturaActionPerformed(evt);
            }
        });
        JPeditarJuego.add(txtRutaminiatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 460, -1));

        btnAccion.setBackground(new java.awt.Color(6, 11, 25));
        btnAccion.setForeground(new java.awt.Color(204, 204, 204));
        btnAccion.setText("Accion");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });
        JPeditarJuego.add(btnAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 720, -1, -1));

        btnTerror.setBackground(new java.awt.Color(6, 11, 25));
        btnTerror.setForeground(new java.awt.Color(204, 204, 204));
        btnTerror.setText("Terror");
        JPeditarJuego.add(btnTerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 720, -1, -1));

        btnAventura.setBackground(new java.awt.Color(6, 11, 25));
        btnAventura.setForeground(new java.awt.Color(204, 204, 204));
        btnAventura.setText("Aventura");
        JPeditarJuego.add(btnAventura, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 720, -1, -1));

        btnMultijugador.setBackground(new java.awt.Color(6, 11, 25));
        btnMultijugador.setForeground(new java.awt.Color(204, 204, 204));
        btnMultijugador.setText("Multijugador");
        JPeditarJuego.add(btnMultijugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 720, -1, -1));

        btnMundoAbierto.setBackground(new java.awt.Color(6, 11, 25));
        btnMundoAbierto.setForeground(new java.awt.Color(204, 204, 204));
        btnMundoAbierto.setText("Mundo abierto");
        JPeditarJuego.add(btnMundoAbierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 720, -1, -1));

        GuardarEdicion.setBackground(new java.awt.Color(6, 11, 25));
        GuardarEdicion.setFont(new java.awt.Font("Candara Light", 1, 28)); // NOI18N
        GuardarEdicion.setForeground(new java.awt.Color(204, 204, 204));
        GuardarEdicion.setText("GUARDAR");
        GuardarEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarEdicionActionPerformed(evt);
            }
        });
        JPeditarJuego.add(GuardarEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 770, 400, 70));

        txtRequisitosMin.setBackground(new java.awt.Color(6, 11, 25));
        txtRequisitosMin.setColumns(20);
        txtRequisitosMin.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        txtRequisitosMin.setForeground(new java.awt.Color(255, 255, 255));
        txtRequisitosMin.setLineWrap(true);
        txtRequisitosMin.setRows(5);
        txtRequisitosMin.setText("Sistema Operativo:\nCPU: \nRAM:\nGráficos:\nDirectX 12\nConexión a internet ");
        txtRequisitosMin.setWrapStyleWord(true);
        SCRM.setViewportView(txtRequisitosMin);

        JPeditarJuego.add(SCRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 350, 120));

        jButton1.setBackground(new java.awt.Color(6, 11, 25));
        jButton1.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        JPeditarJuego.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, -1, 30));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("IMAGEN Portada");
        JPeditarJuego.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        txtrutaportada.setBackground(new java.awt.Color(6, 11, 25));
        txtrutaportada.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        txtrutaportada.setForeground(new java.awt.Color(255, 255, 255));
        txtrutaportada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JPeditarJuego.add(txtrutaportada, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 460, -1));

        jButton2.setBackground(new java.awt.Color(6, 11, 25));
        jButton2.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        JPeditarJuego.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPeditarJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPeditarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarEdicionActionPerformed
        
        
        
        try {
            j.setDescripcion(txtDescripcion.getText());
            j.setPrecio(txtPrecio.getText());
            j.setDirminiatura(txtRutaminiatura.getText());
            j.setDirportada(txtrutaportada.getText());
            j.setRequisitosMIn(txtRequisitosMin.getText());
            j.setRequisitosRec(txtRequisitosrec.getText());
            j.setDirjuego(txtRutajuego.getText());
            String clasificacion = "";
            if (btnAccion.isSelected()) {
                clasificacion = "Accion";
            }
            if (btnAventura.isSelected()) {
                clasificacion = clasificacion + "Aventura";
            }
            if (btnMultijugador.isSelected()) {
                clasificacion = clasificacion + "Multijugador";
            }
            if (btnMundoAbierto.isSelected()) {
                clasificacion = clasificacion + "Mundo Abierto";
            }
            if (btnTerror.isSelected()) {
                clasificacion = clasificacion + "Terror";
            }
            j.getClasificacion().setTipo(clasificacion);
            
            cjuego.edit(j);
            
            this.setVisible(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al editar el juego");
        }
                
    }//GEN-LAST:event_GuardarEdicionActionPerformed

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccionActionPerformed

    private void txtRutajuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutajuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutajuegoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtRutaminiaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaminiaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaminiaturaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarJuego().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarEdicion;
    private javax.swing.JPanel JPeditarJuego;
    private javax.swing.JScrollPane SCRM;
    private javax.swing.JScrollPane SCRR;
    private javax.swing.JScrollPane SCdes;
    private javax.swing.JRadioButton btnAccion;
    private javax.swing.JRadioButton btnAventura;
    private javax.swing.JRadioButton btnMultijugador;
    private javax.swing.JRadioButton btnMundoAbierto;
    private javax.swing.JRadioButton btnTerror;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombreJuego;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextArea txtRequisitosMin;
    private javax.swing.JTextArea txtRequisitosrec;
    private javax.swing.JTextField txtRutajuego;
    private javax.swing.JTextField txtRutaminiatura;
    private javax.swing.JTextField txtrutaportada;
    // End of variables declaration//GEN-END:variables
}
