/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Usuario iTC
 */
public class INICIOTIENDA extends javax.swing.JFrame {

    /**
     * Creates new form INICIO
     */
    public INICIOTIENDA() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel2 = new javax.swing.JPanel();
        lblTienda5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        JPapartadoTienda = new javax.swing.JPanel();
        JPjuegosTienda = new javax.swing.JScrollPane();
        JPjuegoBuscado = new javax.swing.JPanel();
        JPBuscado1 = new javax.swing.JPanel();
        lblNombreB1 = new javax.swing.JLabel();
        lblMiniatura1 = new javax.swing.JLabel();
        lblPrecioB1 = new javax.swing.JLabel();
        lblValorB1 = new javax.swing.JLabel();
        JPBuscado2 = new javax.swing.JPanel();
        lblNombreB2 = new javax.swing.JLabel();
        lblMiniatura2 = new javax.swing.JLabel();
        lblPrecioB2 = new javax.swing.JLabel();
        lblValorB2 = new javax.swing.JLabel();
        JPBuscado3 = new javax.swing.JPanel();
        lblNombreB3 = new javax.swing.JLabel();
        lblMiniatura3 = new javax.swing.JLabel();
        lblPrecioB3 = new javax.swing.JLabel();
        lblValorB3 = new javax.swing.JLabel();
        JPBuscado4 = new javax.swing.JPanel();
        lblNombreB4 = new javax.swing.JLabel();
        lblMiniatura4 = new javax.swing.JLabel();
        lblPrecioB4 = new javax.swing.JLabel();
        lblValorB4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        JPBuscado5 = new javax.swing.JPanel();
        lblNombreB5 = new javax.swing.JLabel();
        lblMiniatura5 = new javax.swing.JLabel();
        lblPrecioB5 = new javax.swing.JLabel();
        lblValorB5 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnBuscarJuegoT = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTienda4 = new javax.swing.JLabel();
        lblTienda2 = new javax.swing.JLabel();
        lblTienda1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1440, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 50));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTienda5.setFont(new java.awt.Font("Lucida Bright", 0, 28)); // NOI18N
        lblTienda5.setForeground(new java.awt.Color(255, 255, 255));
        lblTienda5.setText("Mis juegos");
        lblTienda5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienda5MouseEntered(evt);
            }
        });
        jPanel2.add(lblTienda5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 190, 50));

        jList1.setBackground(new java.awt.Color(6, 11, 25));
        jList1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(204, 204, 204));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Assasins Creed: Valhala", "Call of Duty Cold War" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionBackground(new java.awt.Color(102, 153, 255));
        jScrollPane1.setViewportView(jList1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, 380));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 310, 960));

        JPapartadoTienda.setBackground(new java.awt.Color(0, 0, 0, 100));
        JPapartadoTienda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPjuegosTienda.setToolTipText("");
        JPjuegosTienda.setHorizontalScrollBar(null);

        JPjuegoBuscado.setBackground(new java.awt.Color(6, 11, 25));
        JPjuegoBuscado.setForeground(new java.awt.Color(27, 21, 21));
        JPjuegoBuscado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPBuscado1.setBackground(new java.awt.Color(6, 11, 25));
        JPBuscado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPBuscado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBuscado1MouseClicked(evt);
            }
        });
        JPBuscado1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreB1.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreB1.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        lblNombreB1.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreB1.setText("Call of Duty®: Black Ops Cold War");
        JPBuscado1.add(lblNombreB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        lblMiniatura1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiniatura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cold war 2_miniatura.jpg"))); // NOI18N
        JPBuscado1.add(lblMiniatura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblPrecioB1.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblPrecioB1.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioB1.setText("PVP:99,99");
        JPBuscado1.add(lblPrecioB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        lblValorB1.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValorB1.setForeground(new java.awt.Color(255, 255, 255));
        lblValorB1.setText("V: 4.8/5");
        JPBuscado1.add(lblValorB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        JPjuegoBuscado.add(JPBuscado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1550, 230));

        JPBuscado2.setBackground(new java.awt.Color(6, 11, 25));
        JPBuscado2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPBuscado2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreB2.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreB2.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        lblNombreB2.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreB2.setText("Call of Duty®: Black Ops IV");
        JPBuscado2.add(lblNombreB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        lblMiniatura2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiniatura2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/blackops4_miniatura.jpg"))); // NOI18N
        JPBuscado2.add(lblMiniatura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblPrecioB2.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblPrecioB2.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioB2.setText("PVP:69,99");
        JPBuscado2.add(lblPrecioB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        lblValorB2.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValorB2.setForeground(new java.awt.Color(255, 255, 255));
        lblValorB2.setText("V: 4.0/5");
        JPBuscado2.add(lblValorB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        JPjuegoBuscado.add(JPBuscado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 230));

        JPBuscado3.setBackground(new java.awt.Color(6, 11, 25));
        JPBuscado3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPBuscado3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreB3.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreB3.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        lblNombreB3.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreB3.setText("Call of Duty®: Black Ops III");
        JPBuscado3.add(lblNombreB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        lblMiniatura3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiniatura3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/blackops3_miniatura.jpg"))); // NOI18N
        JPBuscado3.add(lblMiniatura3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblPrecioB3.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblPrecioB3.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioB3.setText("79.99");
        JPBuscado3.add(lblPrecioB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        lblValorB3.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValorB3.setForeground(new java.awt.Color(255, 255, 255));
        lblValorB3.setText("V: 4.9/5");
        JPBuscado3.add(lblValorB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        JPjuegoBuscado.add(JPBuscado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 1550, 230));

        JPBuscado4.setBackground(new java.awt.Color(6, 11, 25));
        JPBuscado4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPBuscado4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreB4.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreB4.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        lblNombreB4.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreB4.setText("Call of Duty®: Black Ops II");
        JPBuscado4.add(lblNombreB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        lblMiniatura4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiniatura4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/blackops2_miniatura.jpg"))); // NOI18N
        JPBuscado4.add(lblMiniatura4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblPrecioB4.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblPrecioB4.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioB4.setText("49,99");
        JPBuscado4.add(lblPrecioB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        lblValorB4.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValorB4.setForeground(new java.awt.Color(255, 255, 255));
        lblValorB4.setText("V: 4.9/5");
        JPBuscado4.add(lblValorB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        jPanel14.setBackground(new java.awt.Color(6, 11, 25));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setText("Call of Duty®: Black Ops Cold War");
        jPanel14.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cold war 2_miniatura.jpg"))); // NOI18N
        jPanel14.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        jLabel41.setText("jLabel4");
        jPanel14.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        jLabel42.setText("jLabel4");
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        jPanel15.setBackground(new java.awt.Color(6, 11, 25));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 204, 204));
        jLabel43.setText("Call of Duty®: Black Ops Cold War");
        jPanel15.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cold war 2_miniatura.jpg"))); // NOI18N
        jPanel15.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        jLabel45.setText("jLabel4");
        jPanel15.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        jLabel46.setText("jLabel4");
        jPanel15.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 1550, 230));

        JPBuscado4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 780, 1550, 230));

        JPjuegoBuscado.add(JPBuscado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, 1550, 230));

        JPBuscado5.setBackground(new java.awt.Color(6, 11, 25));
        JPBuscado5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPBuscado5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreB5.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreB5.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        lblNombreB5.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreB5.setText("Call of Duty®: Black Ops I");
        JPBuscado5.add(lblNombreB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        lblMiniatura5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiniatura5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/blackops1_miniatura.jpg"))); // NOI18N
        JPBuscado5.add(lblMiniatura5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblPrecioB5.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblPrecioB5.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioB5.setText("29,99");
        JPBuscado5.add(lblPrecioB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        lblValorB5.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValorB5.setForeground(new java.awt.Color(255, 255, 255));
        lblValorB5.setText("V: 4.8/5");
        JPBuscado5.add(lblValorB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        JPjuegoBuscado.add(JPBuscado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1030, -1, 230));

        JPjuegosTienda.setViewportView(JPjuegoBuscado);

        JPapartadoTienda.add(JPjuegosTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1610, 910));

        txtbuscar.setBackground(new java.awt.Color(51, 51, 51));
        txtbuscar.setFont(new java.awt.Font("Eras Light ITC", 0, 24)); // NOI18N
        txtbuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscar.setText("Call of duty black ops");
        JPapartadoTienda.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 50));

        btnBuscarJuegoT.setBackground(new java.awt.Color(6, 11, 25));
        btnBuscarJuegoT.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnBuscarJuegoT.setForeground(new java.awt.Color(102, 153, 255));
        btnBuscarJuegoT.setText("BUSCAR");
        btnBuscarJuegoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarJuegoTActionPerformed(evt);
            }
        });
        JPapartadoTienda.add(btnBuscarJuegoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 200, 50));

        getContentPane().add(JPapartadoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 1610, 960));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTienda4.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblTienda4.setForeground(new java.awt.Color(204, 204, 204));
        lblTienda4.setText("eLJhandRy");
        lblTienda4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienda4MouseEntered(evt);
            }
        });
        jPanel1.add(lblTienda4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 20, 110, 40));

        lblTienda2.setFont(new java.awt.Font("Lucida Bright", 0, 28)); // NOI18N
        lblTienda2.setForeground(new java.awt.Color(255, 255, 255));
        lblTienda2.setText("Tendencias");
        lblTienda2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienda2MouseEntered(evt);
            }
        });
        jPanel1.add(lblTienda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 170, 40));

        lblTienda1.setFont(new java.awt.Font("Lucida Bright", 0, 28)); // NOI18N
        lblTienda1.setForeground(new java.awt.Color(102, 153, 255));
        lblTienda1.setText("Tienda");
        lblTienda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienda1MouseEntered(evt);
            }
        });
        jPanel1.add(lblTienda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 170, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/FONDOA1.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1920, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTienda1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTienda1MouseEntered

    private void lblTienda2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTienda2MouseEntered

    private void lblTienda5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTienda5MouseEntered

    private void btnBuscarJuegoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarJuegoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarJuegoTActionPerformed

    private void lblTienda4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTienda4MouseEntered

    private void JPBuscado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBuscado1MouseClicked
        INICIOCOMPRA n=new INICIOCOMPRA();
        this.setVisible(false);
        n.setVisible(true);
    }//GEN-LAST:event_JPBuscado1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INICIOTIENDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INICIOTIENDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INICIOTIENDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INICIOTIENDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INICIOTIENDA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPBuscado1;
    private javax.swing.JPanel JPBuscado2;
    private javax.swing.JPanel JPBuscado3;
    private javax.swing.JPanel JPBuscado4;
    private javax.swing.JPanel JPBuscado5;
    private javax.swing.JPanel JPapartadoTienda;
    private javax.swing.JPanel JPjuegoBuscado;
    private javax.swing.JScrollPane JPjuegosTienda;
    private javax.swing.JButton btnBuscarJuegoT;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMiniatura1;
    private javax.swing.JLabel lblMiniatura2;
    private javax.swing.JLabel lblMiniatura3;
    private javax.swing.JLabel lblMiniatura4;
    private javax.swing.JLabel lblMiniatura5;
    private javax.swing.JLabel lblNombreB1;
    private javax.swing.JLabel lblNombreB2;
    private javax.swing.JLabel lblNombreB3;
    private javax.swing.JLabel lblNombreB4;
    private javax.swing.JLabel lblNombreB5;
    private javax.swing.JLabel lblPrecioB1;
    private javax.swing.JLabel lblPrecioB2;
    private javax.swing.JLabel lblPrecioB3;
    private javax.swing.JLabel lblPrecioB4;
    private javax.swing.JLabel lblPrecioB5;
    private javax.swing.JLabel lblTienda1;
    private javax.swing.JLabel lblTienda2;
    private javax.swing.JLabel lblTienda4;
    private javax.swing.JLabel lblTienda5;
    private javax.swing.JLabel lblValorB1;
    private javax.swing.JLabel lblValorB2;
    private javax.swing.JLabel lblValorB3;
    private javax.swing.JLabel lblValorB4;
    private javax.swing.JLabel lblValorB5;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
