/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Usuario iTC
 */
public class INICIOCOMPRA extends javax.swing.JFrame {

    /**
     * Creates new form INICIO
     */
    public INICIOCOMPRA() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel2 = new javax.swing.JPanel();
        lblTienda5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTienda4 = new javax.swing.JLabel();
        lblTienda2 = new javax.swing.JLabel();
        lblTienda1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1440, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 50));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTienda5.setFont(new java.awt.Font("Lucida Bright", 0, 28)); // NOI18N
        lblTienda5.setForeground(new java.awt.Color(255, 255, 255));
        lblTienda5.setText("Mis juegos");
        lblTienda5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienda5MouseEntered(evt);
            }
        });
        jPanel2.add(lblTienda5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 190, 50));

        jList1.setBackground(new java.awt.Color(6, 11, 25));
        jList1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(204, 204, 204));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Assasins Creed: Valhala", "Call of Duty Cold War" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionBackground(new java.awt.Color(0, 204, 255));
        jList1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jList1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, 380));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 310, 960));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setToolTipText("");
        jScrollPane2.setHorizontalScrollBar(null);

        jPanel5.setBackground(new java.awt.Color(6, 11, 25));
        jPanel5.setForeground(new java.awt.Color(27, 21, 21));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(7, 9, 32));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cold war 2.jpg"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1570, 780));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Call of Duty®: Black Ops Cold War");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 780, -1, 80));

        jButton2.setBackground(new java.awt.Color(6, 11, 25));
        jButton2.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("COMPRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 780, 360, 90));

        jLabel1.setText("Todos los derechos reservados");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 1660, -1, 30));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(6, 11, 25));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Sistema Operativo: Windows 10 64-Bit\nCPU: Intel Core i5-2500K o AMD Ryzen R5 1600X\nRAM: 12 GB de RAM\nHDD (de lanzamiento): 175 GB\nGráficos: NVIDIA GeForce GTX 970 / GTX 1660 Super o Radeon R9 390 / AMD RX 580\nDirectX 12\nConexión a internet");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(null);
        jTextArea2.setCaretColor(new java.awt.Color(6, 11, 25));
        jTextArea2.setSelectionColor(new java.awt.Color(6, 11, 25));
        jScrollPane4.setViewportView(jTextArea2);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1260, 730, 300));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Candara Light", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Recomendados");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1210, -1, -1));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(6, 11, 25));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Call of Duty: Black Ops Cold War es un nueva entrega de la saga de acción bélica first person shooter a cargo de Treyarch junto a Raven y Activision para PC, PlayStation 4, Xbox One, PlayStation 5 y Xbox Series X que nos lleva a la convulsa época de la Guerra Fría. Como operador de élite, seguirás los pasos de una misteriosa figura llamada Perseus, cuya misión es desestabilizar el equilibrio de poder mundial y cambiar el curso de la historia. Adéntrate en esta conspiración global junto con los legendarios personajes Woods, Mason y Hudson, así como con un nuevo plantel de operadores dispuestos a detener una conspiración que lleva décadas urdiéndose. Además de la campaña, los jugadores llevarán un arsenal de armas y equipamiento de la Guerra Fría a la siguiente generación de los modos Multijugador y Zombis.");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setBorder(null);
        jTextArea3.setCaretColor(new java.awt.Color(6, 11, 25));
        jTextArea3.setSelectionColor(new java.awt.Color(6, 11, 25));
        jScrollPane5.setViewportView(jTextArea3);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 970, 1510, 160));

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(6, 11, 25));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("Sistema Operativo: Windows 7 64-Bit (SP1) o Windows 10 64-Bit (v.1803)\nCPU: Intel Core i3-4340 o AMD FX-6300\nRAM: 8 GB de RAM\nHDD: 50 GB (solo multijugador), 175 GB (todos los modos de juego)\nGráficos: NVIDIA GeForce GTX 670 / GeForce GTX 1650 o Radeon HD 7950\nDirectX 12\nConexión a internet ");
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.setBorder(null);
        jTextArea4.setCaretColor(new java.awt.Color(6, 11, 25));
        jTextArea4.setSelectionColor(new java.awt.Color(6, 11, 25));
        jScrollPane6.setViewportView(jTextArea4);

        jPanel5.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1260, 730, 300));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Precio$:99,99");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 820, 240, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Candara Light", 1, 40)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Requisitos:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 1140, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Candara Light", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Minimos:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1210, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Candara Light", 1, 40)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Descripción:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 910, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Valoracion: 4.8/5");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 780, 240, -1));

        jScrollPane2.setViewportView(jPanel5);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1610, 880));

        txtbuscar.setBackground(new java.awt.Color(51, 51, 51));
        txtbuscar.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        txtbuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscar.setText("Call of duty cold war");
        jPanel3.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 50));

        jButton1.setBackground(new java.awt.Color(6, 11, 25));
        jButton1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 153, 255));
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 200, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 1610, 960));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTienda4.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblTienda4.setForeground(new java.awt.Color(204, 204, 204));
        lblTienda4.setText("eLJhandRy");
        lblTienda4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienda4MouseEntered(evt);
            }
        });
        jPanel1.add(lblTienda4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 20, 110, 40));

        lblTienda2.setFont(new java.awt.Font("Lucida Bright", 0, 28)); // NOI18N
        lblTienda2.setForeground(new java.awt.Color(255, 255, 255));
        lblTienda2.setText("Tendencias");
        lblTienda2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTienda2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienda2MouseEntered(evt);
            }
        });
        jPanel1.add(lblTienda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 170, 40));

        lblTienda1.setFont(new java.awt.Font("Lucida Bright", 0, 28)); // NOI18N
        lblTienda1.setForeground(new java.awt.Color(255, 255, 255));
        lblTienda1.setText("Tienda");
        lblTienda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTienda1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienda1MouseEntered(evt);
            }
        });
        jPanel1.add(lblTienda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 170, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/FONDOA1.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1920, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTienda1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTienda1MouseEntered

    private void lblTienda2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTienda2MouseEntered

    private void lblTienda5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTienda5MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblTienda4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTienda4MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Tienda tienda= new Tienda();
        tienda.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblTienda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda1MouseClicked
        INICIOTIENDA n=new INICIOTIENDA();
        this.setVisible(false);
        n.setVisible(true);
    }//GEN-LAST:event_lblTienda1MouseClicked

    private void lblTienda2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda2MouseClicked
        INICIOTENDENCIAS n=new INICIOTENDENCIAS();
        this.setVisible(false);
        n.setVisible(true);
    }//GEN-LAST:event_lblTienda2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INICIOCOMPRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INICIOCOMPRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INICIOCOMPRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INICIOCOMPRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INICIOCOMPRA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel lblTienda1;
    private javax.swing.JLabel lblTienda2;
    private javax.swing.JLabel lblTienda4;
    private javax.swing.JLabel lblTienda5;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
