/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;

/**
 *
 * @author Usuario iTC
 */
public class INICIOADMINISTRACION extends javax.swing.JFrame {

    /**
     * Creates new form INICIO
     */
    public INICIOADMINISTRACION() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lblTienda5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        SCadministracion = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        PesstaañasAdmin = new javax.swing.JTabbedPane();
        Pjuegos = new javax.swing.JPanel();
        PAdministrarJuegos = new javax.swing.JPanel();
        SPjuegos = new javax.swing.JScrollPane();
        JlistJuegos = new javax.swing.JList<>();
        btnAgregarJuego = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        JPAdminRol = new javax.swing.JPanel();
        JPadministrarRoles = new javax.swing.JPanel();
        SpUsers = new javax.swing.JScrollPane();
        JListUsuarios = new javax.swing.JList<>();
        txtbuscar1 = new javax.swing.JTextField();
        btnBuscarUsuario = new javax.swing.JButton();
        btnAsignarAdmin = new javax.swing.JRadioButton();
        btnAsignarUser = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTienda4 = new javax.swing.JLabel();
        lblTienda2 = new javax.swing.JLabel();
        lblTienda1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1440, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 50));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTienda5.setFont(new java.awt.Font("Lucida Bright", 0, 28)); // NOI18N
        lblTienda5.setForeground(new java.awt.Color(255, 255, 255));
        lblTienda5.setText("Mis juegos");
        lblTienda5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienda5MouseEntered(evt);
            }
        });
        jPanel2.add(lblTienda5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 190, 50));

        jList1.setBackground(new java.awt.Color(6, 11, 25));
        jList1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(204, 204, 204));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Assasins Creed: Valhala", "Call of Duty Cold War" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionBackground(new java.awt.Color(102, 153, 255));
        jScrollPane1.setViewportView(jList1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, 380));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 310, 960));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SCadministracion.setToolTipText("");
        SCadministracion.setHorizontalScrollBar(null);

        jPanel5.setBackground(new java.awt.Color(6, 11, 25));
        jPanel5.setForeground(new java.awt.Color(27, 21, 21));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("ADMINISTRACIÓN");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        PesstaañasAdmin.setBackground(new java.awt.Color(6, 11, 25));
        PesstaañasAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PesstaañasAdmin.setForeground(new java.awt.Color(255, 255, 255));
        PesstaañasAdmin.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N

        Pjuegos.setBackground(new java.awt.Color(6, 11, 25));
        Pjuegos.setForeground(new java.awt.Color(27, 21, 21));
        Pjuegos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PAdministrarJuegos.setBackground(new java.awt.Color(6, 11, 25));
        PAdministrarJuegos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlistJuegos.setBackground(new java.awt.Color(6, 11, 25));
        JlistJuegos.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        JlistJuegos.setForeground(new java.awt.Color(255, 255, 255));
        JlistJuegos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Assassins creed: Valhala", "Call of duty black ops cold war", "Crisis 1", "Counter Strike global ofensive", "Halo Mastershif collletion", "Need for speed Hot persuit" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JlistJuegos.setToolTipText("");
        SPjuegos.setViewportView(JlistJuegos);

        PAdministrarJuegos.add(SPjuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 680, 550));

        btnAgregarJuego.setBackground(new java.awt.Color(6, 11, 25));
        btnAgregarJuego.setFont(new java.awt.Font("Candara Light", 1, 28)); // NOI18N
        btnAgregarJuego.setForeground(new java.awt.Color(204, 204, 204));
        btnAgregarJuego.setText("AGREGAR NUEVO JUEGO");
        btnAgregarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarJuegoActionPerformed(evt);
            }
        });
        PAdministrarJuegos.add(btnAgregarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, 400, 70));

        btnEliminar.setBackground(new java.awt.Color(6, 11, 25));
        btnEliminar.setFont(new java.awt.Font("Candara Light", 1, 28)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(204, 204, 204));
        btnEliminar.setText("DAR DE BAJA/ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        PAdministrarJuegos.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 470, 400, 70));

        btnEditar.setBackground(new java.awt.Color(6, 11, 25));
        btnEditar.setFont(new java.awt.Font("Candara Light", 1, 28)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(204, 204, 204));
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        PAdministrarJuegos.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, 400, 70));

        txtbuscar.setBackground(new java.awt.Color(51, 51, 51));
        txtbuscar.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        txtbuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscar.setText("Call of duty cold war");
        PAdministrarJuegos.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 420, 50));

        btnBuscar.setBackground(new java.awt.Color(6, 11, 25));
        btnBuscar.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(102, 153, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        PAdministrarJuegos.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 200, 50));

        Pjuegos.add(PAdministrarJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1440, 670));

        PesstaañasAdmin.addTab("ADMINISTRAR JUEGOS", Pjuegos);

        JPAdminRol.setBackground(new java.awt.Color(6, 11, 25));
        JPAdminRol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPAdminRol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPadministrarRoles.setBackground(new java.awt.Color(6, 11, 25));
        JPadministrarRoles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JListUsuarios.setBackground(new java.awt.Color(6, 11, 25));
        JListUsuarios.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JListUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        JListUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Carlos Ordoñes", "Jhandry Lapo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JListUsuarios.setToolTipText("");
        SpUsers.setViewportView(JListUsuarios);

        JPadministrarRoles.add(SpUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 680, 550));

        txtbuscar1.setBackground(new java.awt.Color(51, 51, 51));
        txtbuscar1.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        txtbuscar1.setForeground(new java.awt.Color(204, 204, 204));
        JPadministrarRoles.add(txtbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 420, 50));

        btnBuscarUsuario.setBackground(new java.awt.Color(6, 11, 25));
        btnBuscarUsuario.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnBuscarUsuario.setForeground(new java.awt.Color(102, 153, 255));
        btnBuscarUsuario.setText("BUSCAR");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });
        JPadministrarRoles.add(btnBuscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 200, 50));

        btnAsignarAdmin.setBackground(new java.awt.Color(6, 11, 25));
        buttonGroup1.add(btnAsignarAdmin);
        btnAsignarAdmin.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        btnAsignarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarAdmin.setText("ADMINISTRADOR");
        btnAsignarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsignarAdminMouseClicked(evt);
            }
        });
        btnAsignarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarAdminActionPerformed(evt);
            }
        });
        JPadministrarRoles.add(btnAsignarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, -1, -1));

        btnAsignarUser.setBackground(new java.awt.Color(6, 11, 25));
        buttonGroup1.add(btnAsignarUser);
        btnAsignarUser.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        btnAsignarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarUser.setText("USUARIO");
        btnAsignarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarUserActionPerformed(evt);
            }
        });
        JPadministrarRoles.add(btnAsignarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 350, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("SELECIONA EL ROL DEL ESTE USUARIO");
        JPadministrarRoles.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, -1, -1));

        JPAdminRol.add(JPadministrarRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1440, 670));

        PesstaañasAdmin.addTab("ADMINISTRAR ROLES", JPAdminRol);

        jPanel5.add(PesstaañasAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 1490, 760));
        PesstaañasAdmin.getAccessibleContext().setAccessibleName("JUEGOS");

        SCadministracion.setViewportView(jPanel5);

        jPanel3.add(SCadministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 930));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 1610, 960));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTienda4.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        lblTienda4.setForeground(new java.awt.Color(204, 204, 204));
        lblTienda4.setText("eLJhandRy");
        lblTienda4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienda4MouseEntered(evt);
            }
        });
        jPanel1.add(lblTienda4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 20, 140, 40));

        lblTienda2.setFont(new java.awt.Font("Lucida Bright", 0, 28)); // NOI18N
        lblTienda2.setForeground(new java.awt.Color(255, 255, 255));
        lblTienda2.setText("Tendencias");
        lblTienda2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienda2MouseEntered(evt);
            }
        });
        jPanel1.add(lblTienda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 170, 40));

        lblTienda1.setFont(new java.awt.Font("Lucida Bright", 0, 28)); // NOI18N
        lblTienda1.setForeground(new java.awt.Color(255, 255, 255));
        lblTienda1.setText("Tienda");
        lblTienda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienda1MouseEntered(evt);
            }
        });
        jPanel1.add(lblTienda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 170, 40));

        jButton1.setBackground(new java.awt.Color(6, 11, 25));
        jButton1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 153, 255));
        jButton1.setText("ADMINISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 20, 200, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/FONDOA1.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1920, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTienda1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTienda1MouseEntered

    private void lblTienda2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTienda2MouseEntered

    private void lblTienda5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTienda5MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblTienda4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienda4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTienda4MouseEntered

    private void btnAgregarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarJuegoActionPerformed
       AnadirJuego nuevo=new AnadirJuego();
       nuevo.setVisible(true);
    }//GEN-LAST:event_btnAgregarJuegoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        JOptionPane.showConfirmDialog(null, "Estas seguro de dar de baja/eliminar este juego", "Confirmar",WIDTH);        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      EditarJuego nuevo=new EditarJuego();
       nuevo.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btnAsignarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarAdminMouseClicked
        
    }//GEN-LAST:event_btnAsignarAdminMouseClicked

    private void btnAsignarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarAdminActionPerformed
        JOptionPane.showConfirmDialog(null, "Estas seguro de asignar este rol", "Confirmar", WIDTH);
    }//GEN-LAST:event_btnAsignarAdminActionPerformed

    private void btnAsignarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarUserActionPerformed
        JOptionPane.showConfirmDialog(null, "Estas seguro de asignar este rol", "Confirmar",WIDTH);
    }//GEN-LAST:event_btnAsignarUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INICIOADMINISTRACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INICIOADMINISTRACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INICIOADMINISTRACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INICIOADMINISTRACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INICIOADMINISTRACION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JListUsuarios;
    private javax.swing.JPanel JPAdminRol;
    private javax.swing.JPanel JPadministrarRoles;
    private javax.swing.JList<String> JlistJuegos;
    private javax.swing.JPanel PAdministrarJuegos;
    private javax.swing.JTabbedPane PesstaañasAdmin;
    private javax.swing.JPanel Pjuegos;
    private javax.swing.JScrollPane SCadministracion;
    private javax.swing.JScrollPane SPjuegos;
    private javax.swing.JScrollPane SpUsers;
    private javax.swing.JButton btnAgregarJuego;
    private javax.swing.JRadioButton btnAsignarAdmin;
    private javax.swing.JRadioButton btnAsignarUser;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTienda1;
    private javax.swing.JLabel lblTienda2;
    private javax.swing.JLabel lblTienda4;
    private javax.swing.JLabel lblTienda5;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtbuscar1;
    // End of variables declaration//GEN-END:variables
}
