/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.JuegoJpaController;
import Controlador.RolJpaController;
import Controlador.UsuarioJpaController;
import Entidades.Juego;
import Entidades.Rol;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario iTC
 */
public class paginaInicio extends javax.swing.JFrame {

    Controlador.JuegoJpaController cjuego = new JuegoJpaController();
    Controlador.UsuarioJpaController cusuario = new UsuarioJpaController();
    Controlador.RolJpaController crol = new RolJpaController();
    List<Entidades.Juego> listaJ = cjuego.findJuegoEntities();
    List<Entidades.Juego> listaedit = cjuego.findJuegoEntities();
    List<Entidades.Usuario> listauser = cusuario.findUsuarioEntities();

    /**
     * Creates new form INICIO
     */
    public paginaInicio() {

        // Codigo de ordenacion de valoraciones de juego para las tendencias (mayor a menor valorados)
        initComponents();
        setResizable(false);

        DefaultListModel modelousu = new DefaultListModel();
        for (int i = 0; i < listauser.size(); i++) {
            modelousu.addElement(listauser.get(i).getCuentauser().getNickname());
        }
        JListUsuarios.setModel(modelousu);
        JLMisjuegos.setVisible(true);
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < listaJ.size(); i++) {
            modelo.addElement(listaJ.get(i).getNombre());
        }
        JlistJuegosadmin.setModel(modelo);
        JlistJuegosadmin.setVisible(true);

        Entidades.Juego[] ListaT = new Entidades.Juego[9];
        double may = 0;
        double actual = 0;
        Entidades.Juego juego = new Juego();
        for (int i = 0; i < ListaT.length; i++) {
            may = 0;
            actual = 0;
            for (int j = 0; j < listaJ.size(); j++) {
                actual = Double.parseDouble(listaJ.get(j).getValoracion().getValor());
                if (actual >= may) {
                    juego = listaJ.get(j);

                    may = actual;
                }
            }

            ListaT[i] = juego;
            listaJ.remove(juego);
        }
        lblNomT1.setText(ListaT[0].getNombre());
        lblValT1.setText(ListaT[0].getValoracion().getValor());
        lblNomT2.setText(ListaT[1].getNombre());
        lblValT2.setText(ListaT[1].getValoracion().getValor());
        lblNomT3.setText(ListaT[2].getNombre());
        lblValT3.setText(ListaT[2].getValoracion().getValor());
        lblNomT4.setText(ListaT[3].getNombre());
        lblValT4.setText(ListaT[3].getValoracion().getValor());
        lblNomT5.setText(ListaT[4].getNombre());
        lblValT5.setText(ListaT[4].getValoracion().getValor());
        lblNomT6.setText(ListaT[5].getNombre());
        lblValT6.setText(ListaT[5].getValoracion().getValor());
        lblNomT7.setText(ListaT[6].getNombre());
        lblValT7.setText(ListaT[6].getValoracion().getValor());
        lblNomT8.setText(ListaT[7].getNombre());
        lblValT8.setText(ListaT[7].getValoracion().getValor());
        lblNomT9.setText(ListaT[8].getNombre());
        lblValT9.setText(ListaT[8].getValoracion().getValor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        SPgeneral = new javax.swing.JScrollPane();
        pGeneral = new javax.swing.JPanel();
        JPMisjuegos = new javax.swing.JPanel();
        lblMisjuegos = new javax.swing.JLabel();
        SPMisjuegos = new javax.swing.JScrollPane();
        JLMisjuegos = new javax.swing.JList<>();
        JPApartadoTendencias = new javax.swing.JPanel();
        SPtendencias = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        JPtendencia1 = new javax.swing.JPanel();
        lblNomT1 = new javax.swing.JLabel();
        lblMinT1 = new javax.swing.JLabel();
        lblValT1 = new javax.swing.JLabel();
        JPtendencia2 = new javax.swing.JPanel();
        lblNomT2 = new javax.swing.JLabel();
        lblMinT2 = new javax.swing.JLabel();
        lblValT2 = new javax.swing.JLabel();
        JPtendencia3 = new javax.swing.JPanel();
        lblNomT3 = new javax.swing.JLabel();
        lblMinT3 = new javax.swing.JLabel();
        lblValT3 = new javax.swing.JLabel();
        JPtendencia4 = new javax.swing.JPanel();
        lblNomT4 = new javax.swing.JLabel();
        lblMinT4 = new javax.swing.JLabel();
        lblValT4 = new javax.swing.JLabel();
        JPtendencia5 = new javax.swing.JPanel();
        lblNomT5 = new javax.swing.JLabel();
        lblMinT5 = new javax.swing.JLabel();
        lblValT5 = new javax.swing.JLabel();
        JPtendencia6 = new javax.swing.JPanel();
        lblNomT6 = new javax.swing.JLabel();
        lblMinT6 = new javax.swing.JLabel();
        lblValT6 = new javax.swing.JLabel();
        JPtendencia7 = new javax.swing.JPanel();
        lblNomT7 = new javax.swing.JLabel();
        lblMinT7 = new javax.swing.JLabel();
        lblValT7 = new javax.swing.JLabel();
        JPtendencia8 = new javax.swing.JPanel();
        lblNomT8 = new javax.swing.JLabel();
        lblMinT8 = new javax.swing.JLabel();
        lblValT8 = new javax.swing.JLabel();
        JPtendencia9 = new javax.swing.JPanel();
        lblNomT9 = new javax.swing.JLabel();
        lblMinT9 = new javax.swing.JLabel();
        lblValT9 = new javax.swing.JLabel();
        JPapartadoTienda = new javax.swing.JPanel();
        JPjuegosTienda = new javax.swing.JScrollPane();
        JPjuegoBuscado = new javax.swing.JPanel();
        JPBuscado1 = new javax.swing.JPanel();
        lblNombreB1 = new javax.swing.JLabel();
        lblMiniatura1 = new javax.swing.JLabel();
        lblPrecioB1 = new javax.swing.JLabel();
        lblValorB1 = new javax.swing.JLabel();
        JPBuscado2 = new javax.swing.JPanel();
        lblNombreB2 = new javax.swing.JLabel();
        lblMiniatura2 = new javax.swing.JLabel();
        lblPrecioB2 = new javax.swing.JLabel();
        lblValorB2 = new javax.swing.JLabel();
        JPBuscado3 = new javax.swing.JPanel();
        lblNombreB3 = new javax.swing.JLabel();
        lblMiniatura3 = new javax.swing.JLabel();
        lblPrecioB3 = new javax.swing.JLabel();
        lblValorB3 = new javax.swing.JLabel();
        JPBuscado4 = new javax.swing.JPanel();
        lblNombreB4 = new javax.swing.JLabel();
        lblMiniatura4 = new javax.swing.JLabel();
        lblPrecioB4 = new javax.swing.JLabel();
        lblValorB4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        JPBuscado5 = new javax.swing.JPanel();
        lblNombreB5 = new javax.swing.JLabel();
        lblMiniatura5 = new javax.swing.JLabel();
        lblPrecioB5 = new javax.swing.JLabel();
        lblValorB5 = new javax.swing.JLabel();
        txtbuscar2 = new javax.swing.JTextField();
        btnBuscarJuegoT = new javax.swing.JButton();
        JPapartadoComprar = new javax.swing.JPanel();
        SPJuego = new javax.swing.JScrollPane();
        JPjuego = new javax.swing.JPanel();
        lblPortada = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnComprarJuego = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SPRRe = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        JPdescripcionjuego = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        JPrequisitosMi = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        lblPrecio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblValoracion = new javax.swing.JLabel();
        txtbuscar3 = new javax.swing.JTextField();
        btnBuscarJuego = new javax.swing.JButton();
        jPApartadoAdmin = new javax.swing.JPanel();
        SCadministracion = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        PesstaañasAdmin = new javax.swing.JTabbedPane();
        Pjuegos = new javax.swing.JPanel();
        PAdministrarJuegos = new javax.swing.JPanel();
        SPjuegos = new javax.swing.JScrollPane();
        JlistJuegosadmin = new javax.swing.JList<>();
        btnAgregarJuego = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        JPAdminRol = new javax.swing.JPanel();
        JPadministrarRoles = new javax.swing.JPanel();
        SpUsers = new javax.swing.JScrollPane();
        JListUsuarios = new javax.swing.JList<>();
        txtbuscarusuario = new javax.swing.JTextField();
        btnBuscarUsuario = new javax.swing.JButton();
        btnAsignarAdmin = new javax.swing.JRadioButton();
        btnAsignarUser = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        JPmenu = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblTendencias = new javax.swing.JLabel();
        lblTienda = new javax.swing.JLabel();
        btnAdministrar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SPgeneral.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        pGeneral.setMinimumSize(new java.awt.Dimension(1922, 780));
        pGeneral.setPreferredSize(new java.awt.Dimension(1922, 720));
        pGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPMisjuegos.setBackground(new java.awt.Color(0, 0, 0, 50));
        JPMisjuegos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPMisjuegos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMisjuegos.setFont(new java.awt.Font("Lucida Bright", 0, 28)); // NOI18N
        lblMisjuegos.setForeground(new java.awt.Color(255, 255, 255));
        lblMisjuegos.setText("Mis juegos");
        lblMisjuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMisjuegosMouseEntered(evt);
            }
        });
        JPMisjuegos.add(lblMisjuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 190, 50));

        JLMisjuegos.setBackground(new java.awt.Color(6, 11, 25));
        JLMisjuegos.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        JLMisjuegos.setForeground(new java.awt.Color(204, 204, 204));
        JLMisjuegos.setSelectionBackground(new java.awt.Color(102, 153, 255));
        SPMisjuegos.setViewportView(JLMisjuegos);

        JPMisjuegos.add(SPMisjuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, 380));

        pGeneral.add(JPMisjuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 310, 870));

        JPApartadoTendencias.setBackground(new java.awt.Color(0, 0, 0, 100));
        JPApartadoTendencias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SPtendencias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SPtendencias.setToolTipText("");
        SPtendencias.setHorizontalScrollBar(null);

        jPanel5.setBackground(new java.awt.Color(6, 11, 25));
        jPanel5.setForeground(new java.awt.Color(27, 21, 21));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPtendencia1.setBackground(new java.awt.Color(6, 11, 25));
        JPtendencia1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPtendencia1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomT1.setBackground(new java.awt.Color(255, 255, 255));
        lblNomT1.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblNomT1.setForeground(new java.awt.Color(204, 204, 204));
        lblNomT1.setText("Call of Duty®: Black Ops III");
        JPtendencia1.add(lblNomT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 390, 110));

        lblMinT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPtendencia1.add(lblMinT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblValT1.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValT1.setForeground(new java.awt.Color(255, 255, 255));
        lblValT1.setText("V: 4.9/5");
        JPtendencia1.add(lblValT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 180, 100));

        jPanel5.add(JPtendencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 230));

        JPtendencia2.setBackground(new java.awt.Color(6, 11, 25));
        JPtendencia2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPtendencia2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomT2.setBackground(new java.awt.Color(255, 255, 255));
        lblNomT2.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblNomT2.setForeground(new java.awt.Color(204, 204, 204));
        lblNomT2.setText("Call of Duty®: Black Ops II");
        JPtendencia2.add(lblNomT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 370, 110));

        lblMinT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPtendencia2.add(lblMinT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblValT2.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValT2.setForeground(new java.awt.Color(255, 255, 255));
        lblValT2.setText("V: 4.9/5");
        JPtendencia2.add(lblValT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 180, 100));

        jPanel5.add(JPtendencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 780, 230));

        JPtendencia3.setBackground(new java.awt.Color(6, 11, 25));
        JPtendencia3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPtendencia3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomT3.setBackground(new java.awt.Color(255, 255, 255));
        lblNomT3.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblNomT3.setForeground(new java.awt.Color(204, 204, 204));
        lblNomT3.setText("Call of Duty®: Black Ops I");
        JPtendencia3.add(lblNomT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 340, 110));

        lblMinT3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPtendencia3.add(lblMinT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblValT3.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValT3.setForeground(new java.awt.Color(255, 255, 255));
        lblValT3.setText("V: 4.8/5");
        JPtendencia3.add(lblValT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 180, 100));

        jPanel5.add(JPtendencia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 780, 230));

        JPtendencia4.setBackground(new java.awt.Color(6, 11, 25));
        JPtendencia4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPtendencia4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomT4.setBackground(new java.awt.Color(255, 255, 255));
        lblNomT4.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblNomT4.setForeground(new java.awt.Color(204, 204, 204));
        lblNomT4.setText("Call of Duty®: Black Ops Cold War");
        JPtendencia4.add(lblNomT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, 110));

        lblMinT4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPtendencia4.add(lblMinT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblValT4.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValT4.setForeground(new java.awt.Color(255, 255, 255));
        lblValT4.setText("V: 4.8/5");
        JPtendencia4.add(lblValT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 180, 100));

        jPanel5.add(JPtendencia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 780, 230));

        JPtendencia5.setBackground(new java.awt.Color(6, 11, 25));
        JPtendencia5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPtendencia5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomT5.setBackground(new java.awt.Color(255, 255, 255));
        lblNomT5.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblNomT5.setForeground(new java.awt.Color(204, 204, 204));
        lblNomT5.setText("Halo: The Master Chief Collection ");
        JPtendencia5.add(lblNomT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 340, 110));

        lblMinT5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPtendencia5.add(lblMinT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblValT5.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValT5.setForeground(new java.awt.Color(255, 255, 255));
        lblValT5.setText("V: 4.7/5");
        JPtendencia5.add(lblValT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 180, 100));

        jPanel5.add(JPtendencia5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 780, 230));

        JPtendencia6.setBackground(new java.awt.Color(6, 11, 25));
        JPtendencia6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPtendencia6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomT6.setBackground(new java.awt.Color(255, 255, 255));
        lblNomT6.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblNomT6.setForeground(new java.awt.Color(204, 204, 204));
        lblNomT6.setText("Phasmophobia");
        JPtendencia6.add(lblNomT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 340, 110));

        lblMinT6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPtendencia6.add(lblMinT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblValT6.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValT6.setForeground(new java.awt.Color(255, 255, 255));
        lblValT6.setText("V: 4.6/5");
        JPtendencia6.add(lblValT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 180, 100));

        jPanel5.add(JPtendencia6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 780, 230));

        JPtendencia7.setBackground(new java.awt.Color(6, 11, 25));
        JPtendencia7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPtendencia7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomT7.setBackground(new java.awt.Color(255, 255, 255));
        lblNomT7.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblNomT7.setForeground(new java.awt.Color(204, 204, 204));
        lblNomT7.setText("FarCry 5");
        JPtendencia7.add(lblNomT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 340, 110));

        lblMinT7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPtendencia7.add(lblMinT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblValT7.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValT7.setForeground(new java.awt.Color(255, 255, 255));
        lblValT7.setText("V: 4.6/5");
        JPtendencia7.add(lblValT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 180, 100));

        jPanel5.add(JPtendencia7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 780, 230));

        JPtendencia8.setBackground(new java.awt.Color(6, 11, 25));
        JPtendencia8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPtendencia8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomT8.setBackground(new java.awt.Color(255, 255, 255));
        lblNomT8.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblNomT8.setForeground(new java.awt.Color(204, 204, 204));
        lblNomT8.setText("Ark: Survival Evolved");
        JPtendencia8.add(lblNomT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 340, 110));

        lblMinT8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPtendencia8.add(lblMinT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblValT8.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValT8.setForeground(new java.awt.Color(255, 255, 255));
        lblValT8.setText("V: 4.5/5");
        JPtendencia8.add(lblValT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 180, 100));

        jPanel5.add(JPtendencia8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 730, 780, 230));

        JPtendencia9.setBackground(new java.awt.Color(6, 11, 25));
        JPtendencia9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPtendencia9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomT9.setBackground(new java.awt.Color(255, 255, 255));
        lblNomT9.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblNomT9.setForeground(new java.awt.Color(204, 204, 204));
        lblNomT9.setText("Call of Duty®: Black Ops IV");
        JPtendencia9.add(lblNomT9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 380, 110));

        lblMinT9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPtendencia9.add(lblMinT9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblValT9.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValT9.setForeground(new java.awt.Color(255, 255, 255));
        lblValT9.setText("V: 4.0/5");
        JPtendencia9.add(lblValT9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 180, 100));

        jPanel5.add(JPtendencia9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 970, 780, 230));

        SPtendencias.setViewportView(jPanel5);

        JPApartadoTendencias.add(SPtendencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 860));

        pGeneral.add(JPApartadoTendencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 1610, 860));

        JPapartadoTienda.setBackground(new java.awt.Color(0, 0, 0, 100));
        JPapartadoTienda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPjuegosTienda.setToolTipText("");
        JPjuegosTienda.setHorizontalScrollBar(null);

        JPjuegoBuscado.setBackground(new java.awt.Color(6, 11, 25));
        JPjuegoBuscado.setForeground(new java.awt.Color(27, 21, 21));
        JPjuegoBuscado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPBuscado1.setBackground(new java.awt.Color(6, 11, 25));
        JPBuscado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPBuscado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBuscado1MouseClicked(evt);
            }
        });
        JPBuscado1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreB1.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreB1.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        lblNombreB1.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreB1.setText("Call of Duty®: Black Ops Cold War");
        JPBuscado1.add(lblNombreB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        lblMiniatura1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiniatura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cold war 2_miniatura.jpg"))); // NOI18N
        JPBuscado1.add(lblMiniatura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblPrecioB1.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblPrecioB1.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioB1.setText("PVP:99,99");
        JPBuscado1.add(lblPrecioB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        lblValorB1.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValorB1.setForeground(new java.awt.Color(255, 255, 255));
        lblValorB1.setText("V: 4.8/5");
        JPBuscado1.add(lblValorB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        JPjuegoBuscado.add(JPBuscado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1550, 230));

        JPBuscado2.setBackground(new java.awt.Color(6, 11, 25));
        JPBuscado2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPBuscado2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreB2.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreB2.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        lblNombreB2.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreB2.setText("Call of Duty®: Black Ops IV");
        JPBuscado2.add(lblNombreB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        lblMiniatura2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiniatura2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/blackops4_miniatura.jpg"))); // NOI18N
        JPBuscado2.add(lblMiniatura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblPrecioB2.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblPrecioB2.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioB2.setText("PVP:69,99");
        JPBuscado2.add(lblPrecioB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        lblValorB2.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValorB2.setForeground(new java.awt.Color(255, 255, 255));
        lblValorB2.setText("V: 4.0/5");
        JPBuscado2.add(lblValorB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        JPjuegoBuscado.add(JPBuscado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 230));

        JPBuscado3.setBackground(new java.awt.Color(6, 11, 25));
        JPBuscado3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPBuscado3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreB3.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreB3.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        lblNombreB3.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreB3.setText("Call of Duty®: Black Ops III");
        JPBuscado3.add(lblNombreB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        lblMiniatura3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiniatura3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/blackops3_miniatura.jpg"))); // NOI18N
        JPBuscado3.add(lblMiniatura3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblPrecioB3.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblPrecioB3.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioB3.setText("79.99");
        JPBuscado3.add(lblPrecioB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        lblValorB3.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValorB3.setForeground(new java.awt.Color(255, 255, 255));
        lblValorB3.setText("V: 4.9/5");
        JPBuscado3.add(lblValorB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        JPjuegoBuscado.add(JPBuscado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 1550, 230));

        JPBuscado4.setBackground(new java.awt.Color(6, 11, 25));
        JPBuscado4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPBuscado4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreB4.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreB4.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        lblNombreB4.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreB4.setText("Call of Duty®: Black Ops II");
        JPBuscado4.add(lblNombreB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        lblMiniatura4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiniatura4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/blackops2_miniatura.jpg"))); // NOI18N
        JPBuscado4.add(lblMiniatura4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblPrecioB4.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblPrecioB4.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioB4.setText("49,99");
        JPBuscado4.add(lblPrecioB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        lblValorB4.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValorB4.setForeground(new java.awt.Color(255, 255, 255));
        lblValorB4.setText("V: 4.9/5");
        JPBuscado4.add(lblValorB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        jPanel14.setBackground(new java.awt.Color(6, 11, 25));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setText("Call of Duty®: Black Ops Cold War");
        jPanel14.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cold war 2_miniatura.jpg"))); // NOI18N
        jPanel14.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        jLabel41.setText("jLabel4");
        jPanel14.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        jLabel42.setText("jLabel4");
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        jPanel15.setBackground(new java.awt.Color(6, 11, 25));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 204, 204));
        jLabel43.setText("Call of Duty®: Black Ops Cold War");
        jPanel15.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cold war 2_miniatura.jpg"))); // NOI18N
        jPanel15.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        jLabel45.setText("jLabel4");
        jPanel15.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        jLabel46.setText("jLabel4");
        jPanel15.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 1550, 230));

        JPBuscado4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 780, 1550, 230));

        JPjuegoBuscado.add(JPBuscado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, 1550, 230));

        JPBuscado5.setBackground(new java.awt.Color(6, 11, 25));
        JPBuscado5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JPBuscado5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreB5.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreB5.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        lblNombreB5.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreB5.setText("Call of Duty®: Black Ops I");
        JPBuscado5.add(lblNombreB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 110));

        lblMiniatura5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiniatura5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/blackops1_miniatura.jpg"))); // NOI18N
        JPBuscado5.add(lblMiniatura5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 210));

        lblPrecioB5.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblPrecioB5.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioB5.setText("29,99");
        JPBuscado5.add(lblPrecioB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 180, 100));

        lblValorB5.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValorB5.setForeground(new java.awt.Color(255, 255, 255));
        lblValorB5.setText("V: 4.8/5");
        JPBuscado5.add(lblValorB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 180, 100));

        JPjuegoBuscado.add(JPBuscado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1030, -1, 230));

        JPjuegosTienda.setViewportView(JPjuegoBuscado);

        JPapartadoTienda.add(JPjuegosTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1610, 810));

        txtbuscar2.setBackground(new java.awt.Color(51, 51, 51));
        txtbuscar2.setFont(new java.awt.Font("Eras Light ITC", 0, 24)); // NOI18N
        txtbuscar2.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscar2.setText("Call of duty black ops");
        JPapartadoTienda.add(txtbuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 50));

        btnBuscarJuegoT.setBackground(new java.awt.Color(6, 11, 25));
        btnBuscarJuegoT.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnBuscarJuegoT.setForeground(new java.awt.Color(102, 153, 255));
        btnBuscarJuegoT.setText("BUSCAR");
        btnBuscarJuegoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarJuegoTActionPerformed(evt);
            }
        });
        JPapartadoTienda.add(btnBuscarJuegoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 200, 50));

        pGeneral.add(JPapartadoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 1610, 860));

        JPapartadoComprar.setBackground(new java.awt.Color(0, 0, 0, 100));
        JPapartadoComprar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SPJuego.setToolTipText("");
        SPJuego.setHorizontalScrollBar(null);

        JPjuego.setBackground(new java.awt.Color(6, 11, 25));
        JPjuego.setForeground(new java.awt.Color(27, 21, 21));
        JPjuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPortada.setBackground(new java.awt.Color(7, 9, 32));
        lblPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cold war 2.jpg"))); // NOI18N
        JPjuego.add(lblPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1570, 780));

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(204, 204, 204));
        lblNombre.setText("Call of Duty®: Black Ops Cold War");
        JPjuego.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 780, -1, 80));

        btnComprarJuego.setBackground(new java.awt.Color(6, 11, 25));
        btnComprarJuego.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        btnComprarJuego.setForeground(new java.awt.Color(204, 204, 204));
        btnComprarJuego.setText("COMPRAR");
        btnComprarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarJuegoActionPerformed(evt);
            }
        });
        JPjuego.add(btnComprarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 780, 360, 90));

        jLabel1.setText("Todos los derechos reservados");
        JPjuego.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 1660, -1, 30));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(6, 11, 25));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Sistema Operativo: Windows 10 64-Bit\nCPU: Intel Core i5-2500K o AMD Ryzen R5 1600X\nRAM: 12 GB de RAM\nHDD (de lanzamiento): 175 GB\nGráficos: NVIDIA GeForce GTX 970 / GTX 1660 Super o Radeon R9 390 / AMD RX 580\nDirectX 12\nConexión a internet");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(null);
        jTextArea2.setCaretColor(new java.awt.Color(6, 11, 25));
        jTextArea2.setSelectionColor(new java.awt.Color(6, 11, 25));
        SPRRe.setViewportView(jTextArea2);

        JPjuego.add(SPRRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1260, 730, 300));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Candara Light", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Recomendados");
        JPjuego.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1210, -1, -1));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(6, 11, 25));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Call of Duty: Black Ops Cold War es un nueva entrega de la saga de acción bélica first person shooter a cargo de Treyarch junto a Raven y Activision para PC, PlayStation 4, Xbox One, PlayStation 5 y Xbox Series X que nos lleva a la convulsa época de la Guerra Fría. Como operador de élite, seguirás los pasos de una misteriosa figura llamada Perseus, cuya misión es desestabilizar el equilibrio de poder mundial y cambiar el curso de la historia. Adéntrate en esta conspiración global junto con los legendarios personajes Woods, Mason y Hudson, así como con un nuevo plantel de operadores dispuestos a detener una conspiración que lleva décadas urdiéndose. Además de la campaña, los jugadores llevarán un arsenal de armas y equipamiento de la Guerra Fría a la siguiente generación de los modos Multijugador y Zombis.");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setBorder(null);
        jTextArea3.setCaretColor(new java.awt.Color(6, 11, 25));
        jTextArea3.setSelectionColor(new java.awt.Color(6, 11, 25));
        JPdescripcionjuego.setViewportView(jTextArea3);

        JPjuego.add(JPdescripcionjuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 970, 1510, 160));

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(6, 11, 25));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("Sistema Operativo: Windows 7 64-Bit (SP1) o Windows 10 64-Bit (v.1803)\nCPU: Intel Core i3-4340 o AMD FX-6300\nRAM: 8 GB de RAM\nHDD: 50 GB (solo multijugador), 175 GB (todos los modos de juego)\nGráficos: NVIDIA GeForce GTX 670 / GeForce GTX 1650 o Radeon HD 7950\nDirectX 12\nConexión a internet ");
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.setBorder(null);
        jTextArea4.setCaretColor(new java.awt.Color(6, 11, 25));
        jTextArea4.setSelectionColor(new java.awt.Color(6, 11, 25));
        JPrequisitosMi.setViewportView(jTextArea4);

        JPjuego.add(JPrequisitosMi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1260, 730, 300));

        lblPrecio.setBackground(new java.awt.Color(255, 255, 255));
        lblPrecio.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(204, 204, 204));
        lblPrecio.setText("Precio$:99,99");
        lblPrecio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPjuego.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 820, 240, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Candara Light", 1, 40)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Requisitos:");
        JPjuego.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 1140, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Candara Light", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Minimos:");
        JPjuego.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1210, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Candara Light", 1, 40)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Descripción:");
        JPjuego.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 910, -1, -1));

        lblValoracion.setBackground(new java.awt.Color(255, 255, 255));
        lblValoracion.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        lblValoracion.setForeground(new java.awt.Color(204, 204, 204));
        lblValoracion.setText("Valoracion: 4.8/5");
        lblValoracion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPjuego.add(lblValoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 780, 240, -1));

        SPJuego.setViewportView(JPjuego);

        JPapartadoComprar.add(SPJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1610, 810));

        txtbuscar3.setBackground(new java.awt.Color(51, 51, 51));
        txtbuscar3.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        txtbuscar3.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscar3.setText("Call of duty cold war");
        JPapartadoComprar.add(txtbuscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 50));

        btnBuscarJuego.setBackground(new java.awt.Color(6, 11, 25));
        btnBuscarJuego.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnBuscarJuego.setForeground(new java.awt.Color(102, 153, 255));
        btnBuscarJuego.setText("BUSCAR");
        btnBuscarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarJuegoActionPerformed(evt);
            }
        });
        JPapartadoComprar.add(btnBuscarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 200, 50));

        pGeneral.add(JPapartadoComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 1610, 860));

        jPApartadoAdmin.setBackground(new java.awt.Color(0, 0, 0, 100));
        jPApartadoAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SCadministracion.setToolTipText("");
        SCadministracion.setHorizontalScrollBar(null);

        jPanel6.setBackground(new java.awt.Color(6, 11, 25));
        jPanel6.setForeground(new java.awt.Color(27, 21, 21));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("ADMINISTRACIÓN");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        PesstaañasAdmin.setBackground(new java.awt.Color(6, 11, 25));
        PesstaañasAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PesstaañasAdmin.setForeground(new java.awt.Color(255, 255, 255));
        PesstaañasAdmin.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N

        Pjuegos.setBackground(new java.awt.Color(6, 11, 25));
        Pjuegos.setForeground(new java.awt.Color(27, 21, 21));
        Pjuegos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PAdministrarJuegos.setBackground(new java.awt.Color(6, 11, 25));
        PAdministrarJuegos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlistJuegosadmin.setBackground(new java.awt.Color(6, 11, 25));
        JlistJuegosadmin.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        JlistJuegosadmin.setForeground(new java.awt.Color(255, 255, 255));
        JlistJuegosadmin.setToolTipText("");
        SPjuegos.setViewportView(JlistJuegosadmin);

        PAdministrarJuegos.add(SPjuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 680, 550));

        btnAgregarJuego.setBackground(new java.awt.Color(6, 11, 25));
        btnAgregarJuego.setFont(new java.awt.Font("Candara Light", 1, 28)); // NOI18N
        btnAgregarJuego.setForeground(new java.awt.Color(204, 204, 204));
        btnAgregarJuego.setText("AGREGAR NUEVO JUEGO");
        btnAgregarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarJuegoActionPerformed(evt);
            }
        });
        PAdministrarJuegos.add(btnAgregarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, 400, 70));

        btnEliminar.setBackground(new java.awt.Color(6, 11, 25));
        btnEliminar.setFont(new java.awt.Font("Candara Light", 1, 28)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(204, 204, 204));
        btnEliminar.setText("DAR DE BAJA/ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        PAdministrarJuegos.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 470, 400, 70));

        btnEditar.setBackground(new java.awt.Color(6, 11, 25));
        btnEditar.setFont(new java.awt.Font("Candara Light", 1, 28)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(204, 204, 204));
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        PAdministrarJuegos.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, 400, 70));

        txtbuscar.setBackground(new java.awt.Color(51, 51, 51));
        txtbuscar.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        txtbuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        PAdministrarJuegos.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 420, 50));

        btnBuscar.setBackground(new java.awt.Color(6, 11, 25));
        btnBuscar.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(102, 153, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        PAdministrarJuegos.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 200, 50));

        Pjuegos.add(PAdministrarJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1440, 670));

        PesstaañasAdmin.addTab("ADMINISTRAR JUEGOS", Pjuegos);

        JPAdminRol.setBackground(new java.awt.Color(6, 11, 25));
        JPAdminRol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPAdminRol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPadministrarRoles.setBackground(new java.awt.Color(6, 11, 25));
        JPadministrarRoles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JListUsuarios.setBackground(new java.awt.Color(6, 11, 25));
        JListUsuarios.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JListUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        JListUsuarios.setToolTipText("");
        SpUsers.setViewportView(JListUsuarios);

        JPadministrarRoles.add(SpUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 680, 550));

        txtbuscarusuario.setBackground(new java.awt.Color(51, 51, 51));
        txtbuscarusuario.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        txtbuscarusuario.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscarusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarusuarioKeyReleased(evt);
            }
        });
        JPadministrarRoles.add(txtbuscarusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 420, 50));

        btnBuscarUsuario.setBackground(new java.awt.Color(6, 11, 25));
        btnBuscarUsuario.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnBuscarUsuario.setForeground(new java.awt.Color(102, 153, 255));
        btnBuscarUsuario.setText("BUSCAR");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });
        JPadministrarRoles.add(btnBuscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 200, 50));

        btnAsignarAdmin.setBackground(new java.awt.Color(6, 11, 25));
        buttonGroup1.add(btnAsignarAdmin);
        btnAsignarAdmin.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        btnAsignarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarAdmin.setText("ADMINISTRADOR");
        btnAsignarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsignarAdminMouseClicked(evt);
            }
        });
        btnAsignarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarAdminActionPerformed(evt);
            }
        });
        JPadministrarRoles.add(btnAsignarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, -1, -1));

        btnAsignarUser.setBackground(new java.awt.Color(6, 11, 25));
        buttonGroup1.add(btnAsignarUser);
        btnAsignarUser.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        btnAsignarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarUser.setText("USUARIO");
        btnAsignarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarUserActionPerformed(evt);
            }
        });
        JPadministrarRoles.add(btnAsignarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 350, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("SELECIONA EL ROL DEL ESTE USUARIO");
        JPadministrarRoles.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, -1, -1));

        JPAdminRol.add(JPadministrarRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1440, 670));

        PesstaañasAdmin.addTab("ADMINISTRAR ROLES", JPAdminRol);

        jPanel6.add(PesstaañasAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 1490, 760));

        SCadministracion.setViewportView(jPanel6);

        jPApartadoAdmin.add(SCadministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 860));

        pGeneral.add(jPApartadoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 1610, 860));

        JPmenu.setBackground(new java.awt.Color(0, 0, 0, 50));
        JPmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lblUsuario.setText("eLJhandRy");
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseEntered(evt);
            }
        });
        JPmenu.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 20, 110, 40));

        lblTendencias.setFont(new java.awt.Font("Lucida Bright", 0, 28)); // NOI18N
        lblTendencias.setForeground(new java.awt.Color(102, 153, 255));
        lblTendencias.setText("Tendencias");
        lblTendencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTendenciasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTendenciasMouseEntered(evt);
            }
        });
        JPmenu.add(lblTendencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 170, 40));

        lblTienda.setFont(new java.awt.Font("Lucida Bright", 0, 28)); // NOI18N
        lblTienda.setForeground(new java.awt.Color(255, 255, 255));
        lblTienda.setText("Tienda");
        lblTienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTiendaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTiendaMouseEntered(evt);
            }
        });
        JPmenu.add(lblTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 170, 40));

        btnAdministrar.setBackground(new java.awt.Color(6, 11, 25));
        btnAdministrar.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnAdministrar.setForeground(new java.awt.Color(102, 153, 255));
        btnAdministrar.setText("ADMINISTRAR");
        btnAdministrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdministrarMouseClicked(evt);
            }
        });
        btnAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarActionPerformed(evt);
            }
        });
        JPmenu.add(btnAdministrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 20, 200, 50));

        pGeneral.add(JPmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 80));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/FONDOA1.jpg"))); // NOI18N
        pGeneral.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1920, 970));

        SPgeneral.setViewportView(pGeneral);

        getContentPane().add(SPgeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTiendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTiendaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTiendaMouseEntered

    private void lblTendenciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTendenciasMouseEntered

    }//GEN-LAST:event_lblTendenciasMouseEntered

    private void lblMisjuegosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMisjuegosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMisjuegosMouseEntered

    private void lblUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarioMouseEntered

    private void lblTiendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTiendaMouseClicked
        JPapartadoTienda.setVisible(true);
        jPApartadoAdmin.setVisible(false);
        JPApartadoTendencias.setVisible(false);
        lblTienda.setForeground(new java.awt.Color(102, 153, 255));
        lblTendencias.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_lblTiendaMouseClicked

    private void btnAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarActionPerformed
        JPApartadoTendencias.setVisible(false);
        JPapartadoTienda.setVisible(false);
        JPapartadoComprar.setVisible(false);
        jPApartadoAdmin.setVisible(true);
        lblTienda.setForeground(new java.awt.Color(255, 255, 255));
        lblTendencias.setForeground(new java.awt.Color(255, 255, 255));

    }//GEN-LAST:event_btnAdministrarActionPerformed

    private void btnAdministrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministrarMouseClicked


    }//GEN-LAST:event_btnAdministrarMouseClicked

    private void btnAgregarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarJuegoActionPerformed
        AnadirJuego nuevo = new AnadirJuego();
        nuevo.setVisible(true);
    }//GEN-LAST:event_btnAgregarJuegoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        JOptionPane.showConfirmDialog(null, "Estas seguro de dar de baja/eliminar este juego", "Confirmar", WIDTH);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int id = 0;
        for (int i = 0; i < listaedit.size(); i++) {
            if (JlistJuegosadmin.getSelectedValue().equals(listaedit.get(i).getNombre())) {
                id = listaedit.get(i).getIdJuego();
                EditarJuego nuevo = new EditarJuego(id);
                nuevo.setVisible(true);
            }
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btnAsignarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarAdminMouseClicked


    }//GEN-LAST:event_btnAsignarAdminMouseClicked

    private void btnAsignarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarAdminActionPerformed

        Entidades.Usuario user;
        try {
            for (int i = 0; i < listauser.size(); i++) {
                System.out.println("for");
                if (listauser.get(i).getCuentauser().getNickname().equals(JListUsuarios.getSelectedValue())) {

                    try {
                        user = listauser.get(i);

                        user.getRoluser().setIdrol(2);

                        cusuario.edit(user);

                    } catch (Exception ex) {
                        Logger.getLogger(paginaInicio.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(null, "Rol ya asignado");
        }

    }//GEN-LAST:event_btnAsignarAdminActionPerformed

    private void btnAsignarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarUserActionPerformed
        Entidades.Usuario user;
        try {
            for (int i = 0; i < listauser.size(); i++) {
                System.out.println("for");
                if (listauser.get(i).getCuentauser().getNickname().equals(JListUsuarios.getSelectedValue())) {
                    System.out.println("encontrado");
                    try {
                        user = listauser.get(i);
                        System.out.println("user");

                        user.getRoluser().setIdrol(1);
                        System.out.println("asa");
                        cusuario.edit(user);
                        System.out.println("cambiado");

                    } catch (Exception ex) {
                        Logger.getLogger(paginaInicio.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(null, "Rol ya asignado");
        }
    }//GEN-LAST:event_btnAsignarUserActionPerformed

    private void JPBuscado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBuscado1MouseClicked
        jPApartadoAdmin.setVisible(false);
        JPapartadoTienda.setVisible(false);
        JPApartadoTendencias.setVisible(false);
        JPapartadoComprar.setVisible(true);
    }//GEN-LAST:event_JPBuscado1MouseClicked

    private void btnBuscarJuegoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarJuegoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarJuegoTActionPerformed

    private void lblTendenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTendenciasMouseClicked
        jPApartadoAdmin.setVisible(false);
        JPapartadoTienda.setVisible(false);
        JPApartadoTendencias.setVisible(true);
        lblTienda.setForeground(new java.awt.Color(255, 255, 255));
        lblTendencias.setForeground(new java.awt.Color(102, 153, 255));


    }//GEN-LAST:event_lblTendenciasMouseClicked

    private void btnComprarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarJuegoActionPerformed
        Tienda tienda = new Tienda();
        tienda.setVisible(true);
    }//GEN-LAST:event_btnComprarJuegoActionPerformed

    private void btnBuscarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarJuegoActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        cjuego.Buscarjuego(txtbuscar.getText());

        DefaultListModel modelbus = new DefaultListModel();
        for (int i = 0; i < cjuego.Buscarjuego(txtbuscar.getText()).size(); i++) {
            modelbus.addElement(cjuego.Buscarjuego(txtbuscar.getText()).get(i).getNombre());
        }
        JlistJuegosadmin.setModel(modelbus);
        JlistJuegosadmin.setVisible(true);


    }//GEN-LAST:event_txtbuscarKeyReleased

    private void txtbuscarusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarusuarioKeyReleased

        cusuario.Buscarusuario(txtbuscarusuario.getText());

        DefaultListModel modelbus = new DefaultListModel();
        for (int i = 0; i < cusuario.Buscarusuario(txtbuscarusuario.getText()).size(); i++) {
            modelbus.addElement(cusuario.Buscarusuario(txtbuscarusuario.getText()).get(i).getCuentauser().getNickname());
        }
        JListUsuarios.setModel(modelbus);
        JListUsuarios.setVisible(true);


    }//GEN-LAST:event_txtbuscarusuarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paginaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paginaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paginaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paginaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paginaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JLMisjuegos;
    private javax.swing.JList<String> JListUsuarios;
    private javax.swing.JPanel JPAdminRol;
    private javax.swing.JPanel JPApartadoTendencias;
    private javax.swing.JPanel JPBuscado1;
    private javax.swing.JPanel JPBuscado2;
    private javax.swing.JPanel JPBuscado3;
    private javax.swing.JPanel JPBuscado4;
    private javax.swing.JPanel JPBuscado5;
    private javax.swing.JPanel JPMisjuegos;
    private javax.swing.JPanel JPadministrarRoles;
    private javax.swing.JPanel JPapartadoComprar;
    private javax.swing.JPanel JPapartadoTienda;
    private javax.swing.JScrollPane JPdescripcionjuego;
    private javax.swing.JPanel JPjuego;
    private javax.swing.JPanel JPjuegoBuscado;
    private javax.swing.JScrollPane JPjuegosTienda;
    private javax.swing.JPanel JPmenu;
    private javax.swing.JScrollPane JPrequisitosMi;
    private javax.swing.JPanel JPtendencia1;
    private javax.swing.JPanel JPtendencia2;
    private javax.swing.JPanel JPtendencia3;
    private javax.swing.JPanel JPtendencia4;
    private javax.swing.JPanel JPtendencia5;
    private javax.swing.JPanel JPtendencia6;
    private javax.swing.JPanel JPtendencia7;
    private javax.swing.JPanel JPtendencia8;
    private javax.swing.JPanel JPtendencia9;
    private javax.swing.JList<String> JlistJuegosadmin;
    private javax.swing.JPanel PAdministrarJuegos;
    private javax.swing.JTabbedPane PesstaañasAdmin;
    private javax.swing.JPanel Pjuegos;
    private javax.swing.JScrollPane SCadministracion;
    private javax.swing.JScrollPane SPJuego;
    private javax.swing.JScrollPane SPMisjuegos;
    private javax.swing.JScrollPane SPRRe;
    private javax.swing.JScrollPane SPgeneral;
    private javax.swing.JScrollPane SPjuegos;
    private javax.swing.JScrollPane SPtendencias;
    private javax.swing.JScrollPane SpUsers;
    public javax.swing.JButton btnAdministrar;
    private javax.swing.JButton btnAgregarJuego;
    private javax.swing.JRadioButton btnAsignarAdmin;
    private javax.swing.JRadioButton btnAsignarUser;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarJuego;
    private javax.swing.JButton btnBuscarJuegoT;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnComprarJuego;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPApartadoAdmin;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblMinT1;
    private javax.swing.JLabel lblMinT2;
    private javax.swing.JLabel lblMinT3;
    private javax.swing.JLabel lblMinT4;
    private javax.swing.JLabel lblMinT5;
    private javax.swing.JLabel lblMinT6;
    private javax.swing.JLabel lblMinT7;
    private javax.swing.JLabel lblMinT8;
    private javax.swing.JLabel lblMinT9;
    private javax.swing.JLabel lblMiniatura1;
    private javax.swing.JLabel lblMiniatura2;
    private javax.swing.JLabel lblMiniatura3;
    private javax.swing.JLabel lblMiniatura4;
    private javax.swing.JLabel lblMiniatura5;
    private javax.swing.JLabel lblMisjuegos;
    private javax.swing.JLabel lblNomT1;
    private javax.swing.JLabel lblNomT2;
    private javax.swing.JLabel lblNomT3;
    private javax.swing.JLabel lblNomT4;
    private javax.swing.JLabel lblNomT5;
    private javax.swing.JLabel lblNomT6;
    private javax.swing.JLabel lblNomT7;
    private javax.swing.JLabel lblNomT8;
    private javax.swing.JLabel lblNomT9;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreB1;
    private javax.swing.JLabel lblNombreB2;
    private javax.swing.JLabel lblNombreB3;
    private javax.swing.JLabel lblNombreB4;
    private javax.swing.JLabel lblNombreB5;
    private javax.swing.JLabel lblPortada;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioB1;
    private javax.swing.JLabel lblPrecioB2;
    private javax.swing.JLabel lblPrecioB3;
    private javax.swing.JLabel lblPrecioB4;
    private javax.swing.JLabel lblPrecioB5;
    private javax.swing.JLabel lblTendencias;
    private javax.swing.JLabel lblTienda;
    public javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblValT1;
    private javax.swing.JLabel lblValT2;
    private javax.swing.JLabel lblValT3;
    private javax.swing.JLabel lblValT4;
    private javax.swing.JLabel lblValT5;
    private javax.swing.JLabel lblValT6;
    private javax.swing.JLabel lblValT7;
    private javax.swing.JLabel lblValT8;
    private javax.swing.JLabel lblValT9;
    private javax.swing.JLabel lblValorB1;
    private javax.swing.JLabel lblValorB2;
    private javax.swing.JLabel lblValorB3;
    private javax.swing.JLabel lblValorB4;
    private javax.swing.JLabel lblValorB5;
    private javax.swing.JLabel lblValoracion;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JPanel pGeneral;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtbuscar2;
    private javax.swing.JTextField txtbuscar3;
    private javax.swing.JTextField txtbuscarusuario;
    // End of variables declaration//GEN-END:variables
}
