/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CuentaJpaController;
import Controlador.UsuarioJpaController;
import Entidades.Usuario;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario iTC
 */
public class RecuperarContrasena extends javax.swing.JFrame {
    
    int codigo = (int) Math.floor(Math.random() * 5000 + 1);

    /**
     * Creates new form RecuperarContrasena
     */
    public RecuperarContrasena() {
        initComponents();
        setResizable(false);
        setLocation(800, 200);
        btnCancelar.setVisible(false);
        panelguardar.setVisible(false);
        panelverificar.setVisible(false);
        TextPrompt crecuperar = new TextPrompt("Ingrese el correo con el que se registro", txtMailR);
        TextPrompt codigp = new TextPrompt("Escriba el codigo de verificación", txtcodConf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelenviarC = new javax.swing.JPanel();
        txtMailR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEnviarCodigo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        panelverificar = new javax.swing.JPanel();
        txtcodConf = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        btnVerificar1 = new javax.swing.JButton();
        panelguardar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardarNPs = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtPassnueva = new javax.swing.JPasswordField();
        txtPassCOnfir = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recuperación de contraseña");
        setBackground(new java.awt.Color(51, 51, 51));

        panelenviarC.setBackground(new java.awt.Color(6, 11, 25));
        panelenviarC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMailR.setBackground(new java.awt.Color(6, 11, 25));
        txtMailR.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 18)); // NOI18N
        txtMailR.setForeground(new java.awt.Color(255, 255, 255));
        txtMailR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMailR.setBorder(null);
        panelenviarC.add(txtMailR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 377, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Se enviara un codigo de verificación a tu dirección de correo electronico ");
        panelenviarC.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Recuperación de contraseña");
        panelenviarC.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 337, 40));

        btnEnviarCodigo.setBackground(new java.awt.Color(6, 11, 25));
        btnEnviarCodigo.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnEnviarCodigo.setForeground(new java.awt.Color(102, 153, 255));
        btnEnviarCodigo.setText("Enviar el codigo");
        btnEnviarCodigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnviarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCodigoActionPerformed(evt);
            }
        });
        panelenviarC.add(btnEnviarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 210, 50));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        panelenviarC.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 440, 10));

        panelverificar.setBackground(new java.awt.Color(6, 11, 25));
        panelverificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcodConf.setBackground(new java.awt.Color(6, 11, 25));
        txtcodConf.setFont(new java.awt.Font("Candara Light", 0, 24)); // NOI18N
        txtcodConf.setForeground(new java.awt.Color(255, 255, 255));
        txtcodConf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodConf.setBorder(null);
        panelverificar.add(txtcodConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 560, 70));

        btnCancelar.setBackground(new java.awt.Color(6, 11, 25));
        btnCancelar.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(102, 153, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelverificar.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 120, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        panelverificar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 510, 10));

        jLabel6.setBackground(new java.awt.Color(6, 11, 25));
        jLabel6.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingrese el codigo de verificación");
        panelverificar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 360, 40));

        btnVerificar1.setBackground(new java.awt.Color(6, 11, 25));
        btnVerificar1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnVerificar1.setForeground(new java.awt.Color(102, 153, 255));
        btnVerificar1.setText("Verificar");
        btnVerificar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificar1ActionPerformed(evt);
            }
        });
        panelverificar.add(btnVerificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 220, 50));

        panelguardar.setBackground(new java.awt.Color(6, 11, 25));
        panelguardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(6, 11, 25));
        jLabel5.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cambiar contraseña");
        panelguardar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 230, 40));

        btnGuardarNPs.setBackground(new java.awt.Color(6, 11, 25));
        btnGuardarNPs.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnGuardarNPs.setForeground(new java.awt.Color(102, 153, 255));
        btnGuardarNPs.setText("Guardar");
        btnGuardarNPs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarNPs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNPsActionPerformed(evt);
            }
        });
        panelguardar.add(btnGuardarNPs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 210, 50));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        panelguardar.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 340, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        panelguardar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 340, 10));

        txtPassnueva.setBackground(new java.awt.Color(6, 11, 25));
        txtPassnueva.setForeground(new java.awt.Color(204, 204, 204));
        txtPassnueva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassnueva.setBorder(null);
        txtPassnueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassnuevaActionPerformed(evt);
            }
        });
        panelguardar.add(txtPassnueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 340, -1));

        txtPassCOnfir.setBackground(new java.awt.Color(6, 11, 25));
        txtPassCOnfir.setForeground(new java.awt.Color(204, 204, 204));
        txtPassCOnfir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassCOnfir.setBorder(null);
        panelguardar.add(txtPassCOnfir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 340, -1));

        jLabel3.setBackground(new java.awt.Color(6, 11, 25));
        jLabel3.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirmar contraseña");
        panelguardar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 150, 40));

        jLabel7.setBackground(new java.awt.Color(6, 11, 25));
        jLabel7.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nueva contraseña");
        panelguardar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelenviarC, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelguardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelverificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelenviarC, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelguardar, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelverificar, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        Login n = new Login();
        n.setVisible(true);
        

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEnviarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarCodigoActionPerformed
        try {
            //ENVIA UN CORREO CON UN CODIGO AL CORREO DEL QUE SE DESEA RECUPERAR LA CONTRASEÑA
            Controlador.UsuarioJpaController cusuarios = new UsuarioJpaController();
            List<Entidades.Usuario> listaU = cusuarios.findUsuarioEntities();
            boolean verificador = true;
            for (int i = 0; i < listaU.size(); i++) {
                if (listaU.get(i).getCorreo().equals(txtMailR.getText())) {
                    verificador = true;
                    try {
                        //envio de codigo a correo
                        Properties prop = new Properties();
                        prop.setProperty("mail.smtp.host", "smtp.gmail.com");
                        prop.setProperty("mail.smtp.starttls.enable", "true");
                        prop.setProperty("mail.smtp.port", "587");
                        prop.setProperty("mail.smtp.auth", "true");
                        
                        Session sesion = Session.getDefaultInstance(prop);
                        
                        String Remitente = "sstgaming9@gmail.com";
                        String contra = "proyectofinal123";
                        String correoenviar = txtMailR.getText();
                        String asunto = "CODIGO DE CONFIRMACION";
                        String codigoenvio = String.valueOf(codigo);
                        
                        MimeMessage mensaje = new MimeMessage(sesion);
                        mensaje.setFrom(new InternetAddress(Remitente));
                        
                        mensaje.addRecipient(Message.RecipientType.TO, new InternetAddress(correoenviar));
                        mensaje.setSubject(asunto);
                        mensaje.setText(codigoenvio);
                        
                        Transport t = sesion.getTransport("smtp");
                        t.connect(Remitente, contra);
                        t.sendMessage(mensaje, mensaje.getRecipients(Message.RecipientType.TO));
                        t.close();
                        panelenviarC.setVisible(false);
                        panelverificar.setVisible(true);
                    } catch (MessagingException ex) {
                        Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "VERIFICAR EL CORREO INGRESADO");
                    }
                    break;
                } else {
                    verificador = false;
                }
                
            }
            if (verificador == false) {
                JOptionPane.showMessageDialog(null, "El correo que se ingreso no esta registrado");
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error");
            Login n = new Login();
            n.setVisible(true);
            this.setVisible(false);
        }
        

    }//GEN-LAST:event_btnEnviarCodigoActionPerformed

    private void btnGuardarNPsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNPsActionPerformed
        //COMPUEBA DATOS DE LA NUEVA CONTRASEÑA
        Login n = new Login();
        
        try {
            boolean c = true;
            
            if (txtPassnueva.getText().equals(txtPassCOnfir.getText())) {
                c = false;
                if (txtPassnueva.getText().length() < 8) {
                    JOptionPane.showMessageDialog(null, "Las contraseñas debe contener almenos 8 caracteres");
                    c = true;
                    
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden, verificar");
            }
            
            if (c == false) {
                Controlador.CuentaJpaController ccuenta = new CuentaJpaController();
                Controlador.UsuarioJpaController cusuarios = new UsuarioJpaController();
                List<Entidades.Usuario> listaU = cusuarios.findUsuarioEntities();
                boolean verificador = true;
                for (int i = 0; i < listaU.size(); i++) {
                    
                    if (listaU.get(i).getCorreo().equals(txtMailR.getText())) {
                        listaU.get(i).getCuentauser().setContrasena(txtPassnueva.getText());
                        ccuenta.edit(listaU.get(i).getCuentauser());
                        n.setVisible(true);
                        this.setVisible(false);
                    }
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error");
            
            n.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_btnGuardarNPsActionPerformed

    private void txtPassnuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassnuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassnuevaActionPerformed

    private void btnVerificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificar1ActionPerformed
        //VERIFICA QUE ELL CODIGO ENVIADO Y EL QUE SE INGRESO SON CORRECTOS
        if (txtcodConf.getText().equals(String.valueOf(codigo))) {
            panelverificar.setVisible(false);
            panelguardar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "El codigo ingresado es incorrecto");
            btnCancelar.setVisible(true);
            
        }
        

    }//GEN-LAST:event_btnVerificar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviarCodigo;
    private javax.swing.JButton btnGuardarNPs;
    private javax.swing.JButton btnVerificar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel panelenviarC;
    private javax.swing.JPanel panelguardar;
    private javax.swing.JPanel panelverificar;
    private javax.swing.JTextField txtMailR;
    private javax.swing.JPasswordField txtPassCOnfir;
    private javax.swing.JPasswordField txtPassnueva;
    private javax.swing.JTextField txtcodConf;
    // End of variables declaration//GEN-END:variables
}
