/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Usuario iTC
 */
public class RecuperarContrasena extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarContrasena
     */
    public RecuperarContrasena() {
        initComponents();
        setResizable(false);
        setLocation(800, 200);
        panelguardar.setVisible(false);
        panelverificar.setVisible(false);
        TextPrompt crecuperar=new TextPrompt("Correo o nombre de usuario", txtmailrecuperar);
        TextPrompt codigp=new TextPrompt("Escriba el codigo de verificación", txtcodConf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelenviarC = new javax.swing.JPanel();
        txtmailrecuperar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEnviarCodigo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        panelverificar = new javax.swing.JPanel();
        txtcodConf = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        panelguardar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardarNPs = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtPassnueva = new javax.swing.JPasswordField();
        txtPassCOnfir = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recuperación de contraseña");
        setBackground(new java.awt.Color(51, 51, 51));

        panelenviarC.setBackground(new java.awt.Color(6, 11, 25));
        panelenviarC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtmailrecuperar.setBackground(new java.awt.Color(6, 11, 25));
        txtmailrecuperar.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 18)); // NOI18N
        txtmailrecuperar.setForeground(new java.awt.Color(255, 255, 255));
        txtmailrecuperar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmailrecuperar.setBorder(null);
        txtmailrecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailrecuperarActionPerformed(evt);
            }
        });
        panelenviarC.add(txtmailrecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 377, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Se enviara un codigo de verificación a tu dirección de correo electronico ");
        panelenviarC.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Recuperación de contraseña");
        panelenviarC.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 337, 40));

        btnEnviarCodigo.setBackground(new java.awt.Color(6, 11, 25));
        btnEnviarCodigo.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnEnviarCodigo.setForeground(new java.awt.Color(102, 153, 255));
        btnEnviarCodigo.setText("Enviar el codigo");
        btnEnviarCodigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnviarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCodigoActionPerformed(evt);
            }
        });
        panelenviarC.add(btnEnviarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 210, 50));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        panelenviarC.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 440, 10));

        panelverificar.setBackground(new java.awt.Color(6, 11, 25));
        panelverificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcodConf.setBackground(new java.awt.Color(6, 11, 25));
        txtcodConf.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        txtcodConf.setForeground(new java.awt.Color(255, 255, 255));
        txtcodConf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodConf.setBorder(null);
        txtcodConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodConfActionPerformed(evt);
            }
        });
        panelverificar.add(txtcodConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 560, 70));

        btnVerificar.setBackground(new java.awt.Color(6, 11, 25));
        btnVerificar.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnVerificar.setForeground(new java.awt.Color(102, 153, 255));
        btnVerificar.setText("Verificar");
        btnVerificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        panelverificar.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 210, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        panelverificar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 510, 10));

        jLabel6.setBackground(new java.awt.Color(6, 11, 25));
        jLabel6.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingrese el codigo de verificación");
        panelverificar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 360, 40));

        panelguardar.setBackground(new java.awt.Color(6, 11, 25));
        panelguardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(6, 11, 25));
        jLabel5.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cambiar contraseña");
        panelguardar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 230, 40));

        btnGuardarNPs.setBackground(new java.awt.Color(6, 11, 25));
        btnGuardarNPs.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnGuardarNPs.setForeground(new java.awt.Color(102, 153, 255));
        btnGuardarNPs.setText("Guardar");
        btnGuardarNPs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarNPs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNPsActionPerformed(evt);
            }
        });
        panelguardar.add(btnGuardarNPs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 210, 50));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        panelguardar.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 340, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        panelguardar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 340, 10));

        txtPassnueva.setBackground(new java.awt.Color(6, 11, 25));
        txtPassnueva.setForeground(new java.awt.Color(204, 204, 204));
        txtPassnueva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassnueva.setBorder(null);
        txtPassnueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassnuevaActionPerformed(evt);
            }
        });
        panelguardar.add(txtPassnueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 340, -1));

        txtPassCOnfir.setBackground(new java.awt.Color(6, 11, 25));
        txtPassCOnfir.setForeground(new java.awt.Color(204, 204, 204));
        txtPassCOnfir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassCOnfir.setBorder(null);
        panelguardar.add(txtPassCOnfir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 340, -1));

        jLabel3.setBackground(new java.awt.Color(6, 11, 25));
        jLabel3.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirmar contraseña");
        panelguardar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 150, 40));

        jLabel7.setBackground(new java.awt.Color(6, 11, 25));
        jLabel7.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nueva contraseña");
        panelguardar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelenviarC, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelguardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelverificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelenviarC, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelguardar, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelverificar, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmailrecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailrecuperarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailrecuperarActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        panelverificar.setVisible(false);
        panelguardar.setVisible(true);
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void txtcodConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodConfActionPerformed

    private void btnEnviarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarCodigoActionPerformed
    panelenviarC.setVisible(false);
    panelverificar.setVisible(true);
    }//GEN-LAST:event_btnEnviarCodigoActionPerformed

    private void btnGuardarNPsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNPsActionPerformed
        this.setVisible(false);
        Login g=new Login();
        g.setVisible(true);
    }//GEN-LAST:event_btnGuardarNPsActionPerformed

    private void txtPassnuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassnuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassnuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarCodigo;
    private javax.swing.JButton btnGuardarNPs;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel panelenviarC;
    private javax.swing.JPanel panelguardar;
    private javax.swing.JPanel panelverificar;
    private javax.swing.JPasswordField txtPassCOnfir;
    private javax.swing.JPasswordField txtPassnueva;
    private javax.swing.JTextField txtcodConf;
    private javax.swing.JTextField txtmailrecuperar;
    // End of variables declaration//GEN-END:variables
}
